### ISSUE TITLE
Just a quick question, not a bug

### ISSUE THREAD

**Issue by Pendragon51** [diStyApps/ComfyUI-disty-Flow#10]
### Where is the issue?

- [X] The issue is with the "Custom Node 'Flow'"
- [ ] The issue is with a specific flow. Please refer to [Flows repository](https://github.com/diStyApps/flows_lib) if the problem lies with a specific flow.
- [ ] I’m not sure where the issue is

### Bug Description

Just a quick question, I have a workflow for playground 2.5 and I would like to add it to Flow, can you explain to me how to do that? I tried to add a new folder and see if it would update but it didn't, any thoughts?

### Step-by-step instructions to reproduce the issue

none

### Expected Behavior

none

### Current Behavior

none

### Flow Version or Commit

none

### Media and Logs

```Shell
none
```

**Comment by diStyApps** [comment]
You can you can copy existing "Flow" for example "afl_abase" in the "Flows" folder , there are 2 JSON files. the actual workflow wf.json in API format, you have to save you file as API format via comfy, and flowConfig.json.
And you can see how the file are linked together.

For example for CLIP Text Encode (Prompt)
by the node path "6.inputs.text"
Node number "6" you can see it in the workflows on ComfyUI.
inputs
Field name: "text" 

From flowConfig.json 

```
 {
  "id": "yourflowname",
  "name": "Your Flow Name",
  "url": "yourflowname",
  "description": "Basic image generation SD and SDXL",
  "workflowInputs": [
    { "id": "prompt1", "label": "Prompt", "nodePath": "6.inputs.text", "default": "" },
  ],
  "seeders": [],
  "steppers": [],
  "dropdowns": [],
  "multiSteppers": [],
  "dropdownSteppers": [],
  "dimensionSelectors": [],
  "imageLoaders": [],
  "configCustomNodes": []
}
```

From wf.json:  (can be any workflow saved in API format, with some exceptions)

```
  "6": {
    "inputs": {
      "text": "A cartoon happy goat with purple eyes and a black horn in the jungle",
      "clip": [
        "4",
        1
      ]
    },
    "class_type": "CLIPTextEncode",
    "_meta": {
      "title": "CLIP Text Encode (Prompt)"
    }
  },
```


After you do this, restart ComfyUI , it should show up, then you can edit the JSON, without restarting ComfyUI again.

Linker should be ready till the end of the week or so i hope.
