### ISSUE TITLE
[Feature Request]: Edit Image to generate mask 

### ISSUE THREAD

**Issue by SongOnWater** [diStyApps/ComfyUI-disty-Flow#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Summary

I appreciate your awesome work. I just want to know would the Inpainting Functionality in Roadmap will include editing image to generate mask to further processes. 

### Description

I appreciate your awesome work. I just want to know would the Inpainting Functionality in Roadmap will include editing image to generate mask to further processes.

**Comment by diStyApps** [comment]
You will able to save the mask separately.
