### ISSUE TITLE
[Bug]: No preview on a new created Linker Workflow

### ISSUE THREAD

**Issue by VictorDmAlves** [diStyApps/ComfyUI-disty-Flow#14]
### Where is the issue?

- [X] The issue is with the "Custom Node 'Flow'"
- [ ] The issue is with a specific flow. Please refer to [Flows repository](https://github.com/diStyApps/flows_lib) if the problem lies with a specific flow.
- [ ] I’m not sure where the issue is

### Bug Description

There are no preview on the generating image within a created Linker Workflow. I compared with the ones that comes with the project, and that have previews, I've not seen any difference what so ever. Maybe I'm missing something? BTW, nice feature, really cool!

![image](https://github.com/user-attachments/assets/829e2563-284f-4324-bea0-032e97fc017f)

### Step-by-step instructions to reproduce the issue

Created a Workflow using a wf.json from a Flow project, changing the necessary things here and there. Save him as a API and use Linker for adding a new Workflow whithin the Flow. Run it, it does complete sucessfuly, but without a preview.

### Expected Behavior

A preview of the progress, just like the others Flow Workflows.

### Current Behavior

No preview in the created Linker Workflow.

### Flow Version or Commit

0.2.0

### Media and Logs

```Shell
Nothing to add.
```

**Comment by diStyApps** [comment]
Thank you very much.
There should be no difference.
Update ComfyUI and ComfyUI Manager.
Update Flow.
I guess you have enabled preview on ComfyUI Manager.
Open the linker again and load the same workflow and just click preview then click generate, you should a preview, if not try some basic SDXL / SD 1.5 workflow.
if that didn't help press ctrl+shift+K, and print screen the console log while you generate an image.

**Comment by VictorDmAlves** [comment]
> Thank you very much. There should be no difference. Update ComfyUI and ComfyUI Manager. Update Flow. I guess you have enabled preview on ComfyUI Manager. Open the linker again and load the same workflow and just click preview then click generate, you should a preview, if not try some basic SDXL / SD 1.5 workflow. if that didn't help press ctrl+shift+K, and print screen the console log while you generate an image.

Hey man, appreciate the attention. I just check the updates, but still having problem with previews. But I think is some custom workflow that I've installed, since not a single Workflow within Flow is showing a preview now, and even my "Open in MaskEditor" is broken, all grey out, hence my deduction.

I don't use image preview, it's "none" in the Comfy Manager. I tried that command "ctrl+shift+K" but it just open a new window, with the same content, no log. Well, I will seek a alternative, but it's more likely that it's only happening with me. Thanks anyway, looking forward to the new improvements to come!

**Comment by diStyApps** [comment]
In ComfyUI Manager set the preview it to "Auto" and try again.

**Comment by VictorDmAlves** [comment]
You are completely right, turning Auto did the trick, thank you! Maybe you could put a warning on that somewhere? But hey, thank you!

**Comment by diStyApps** [comment]
Yes it is not that clear and you are not the first one, so it is my fault, i have made tutorial about it today.

https://www.youtube.com/watch?v=Ioqs0Gacuo4

But good suggestion ill add some note or something.

Thank you flowing!
