### ISSUE TITLE
[Feature Request]: Generate until stopped

### ISSUE THREAD

**Issue by Pantonia4** [diStyApps/ComfyUI-disty-Flow#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Summary

The option to Generate images until you manually stop it

### Description

Basically just a button that instead of generating a single image, it continues to generate images until you stop. Or let us choose how many images should be generated in a row.

**Comment by Pantonia4** [comment]
Nevermind you can just click generate again to queue multiple generations.

**Comment by diStyApps** [comment]
Thank you for your suggestion, I will add such functionality.
