### ISSUE TITLE
[Feature Request]: Ability to run flow Standalone and runing comfui workflow on remote instance and download the image using websocket_image_save

### ISSUE THREAD

**Issue by sanihaq** [diStyApps/ComfyUI-disty-Flow#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Summary

Well, the title says it all. I (like many) will be grateful for this feature, and I think this will also increase usefulness of this project greatly. thank you.  

### Description

Ability to run flow Standalone and runing comfui workflow on remote instance and download the image using websocket_image_save node

**Comment by diStyApps** [comment]
Thank you, well that was initial plan, but i thought it will be easier for people as an custom node.
Anyway ill probably do a standalone release, just thinking if to use same code or rebuild better version with modern frameworks, maybe both.

**Comment by sanihaq** [comment]
@diStyApps whatever you do, please add the ability to do remote execution of workflow and fetching images to local (automatically)
