### ISSUE TITLE
issues with google chrome 

### ISSUE THREAD

**Issue by nadora35** [diStyApps/ComfyUI-disty-Flow#19]
issues with google chrome only .... every thing is uptodate and working good 
try to uninstall and re ... nothing happen 
![Untitled2222222](https://github.com/user-attachments/assets/372ac367-6717-4096-84a6-9a11aa479716)
![Untitled2222222333333333](https://github.com/user-attachments/assets/5780c7b8-e4ad-4456-a864-fae6b36c554e)

**Comment by Tihf** [comment]
apparently, you do not have the default flux model or its vae, check the red boxes, when it's red it means it's missing, click on them and try selecting a flux model and a vae if you have one.

**Comment by diStyApps** [comment]
It is mainly built for chrome even though do i like Firefox more.
But i mainly use it on chrome.
Try ctrl+f5.
if that didn't help press ctrl+shift+k, and copy the console log.

For the models:
flux_1Dev.safetensors should be in ComfyUI/Models/unet/ 
ae.sft should be in ComfyUI/Models/vae/

**Comment by diStyApps** [comment]
The UI issue is still happening?
