### ISSUE TITLE
[Bug]: WebSocket mixed content

### ISSUE THREAD

**Issue by agarzon** [diStyApps/ComfyUI-disty-Flow#22]
### Where is the issue?

- [ ] The issue is with the "Custom Node 'Flow'"
- [ ] The issue is with a specific flow. Please refer to [Flows repository](https://github.com/diStyApps/flows_lib) if the problem lies with a specific flow.
- [ ] I’m not sure where the issue is

### Bug Description

The websocket does not support WSS when running behind a secure connection via HTTPS.

### Step-by-step instructions to reproduce the issue

Having comfyui running in the cloud behind a secure layer. Example using Cloudflare

### Expected Behavior

The code should identify the request is coming from a HTTPS URL and use WSS for the socket instead WS

### Current Behavior

Does not support HTTPS

### Flow Version or Commit

489831c

### Media and Logs

```Shell
webSocketHandler.js:12 Mixed Content: The page at 'https://xxxx.xxxx.com/flow/2m1x4-base-stable-diffusion' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://xxxx.xxxx.com/ws?clientId=516f38f6-0ee1-4176-a2fb-912b2e443526'. This request has been blocked; this endpoint must be available over WSS.
connect	@	webSocketHandler.js:12
```

### Additional Information

![image](https://github.com/user-attachments/assets/ab3eb1aa-4cfd-4df1-aa01-848c2fb6d249)

**Comment by diStyApps** [comment]
fixed, reopen if issue is comes back.
