### ISSUE TITLE
[Bug]: "Flux - Redux 2 Images" doesn't update the UI after changing images.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [diStyApps/ComfyUI-disty-Flow#24]
### Where is the issue?

- [ ] The issue is with the "Custom Node 'Flow'"
- [ ] The issue is with a specific flow. Please refer to [Flows repository](https://github.com/diStyApps/flows_lib) if the problem lies with a specific flow.
- [X] I’m not sure where the issue is

### Bug Description

I used the "Flux - Redux 2 Images" flow and added my 2 images to it. I then created 5 images and they appear in the "Recent" panel, and each in the centre of the screen, as they were created. I then changed one of the input images and started creating more images, but the "Recent" panel, and the image in centre, do not update, and still show the last image I created before changing the inputs. It is creating and saving new images, but nothing in the UI is updating to show this.

### Step-by-step instructions to reproduce the issue

See above.

### Expected Behavior

The images continue to update in the UI.

### Current Behavior

See first description of the problem.

### Flow Version or Commit

0.3.3

### Media and Logs

```Shell
There is nothing logged as any error to show.
```

**Comment by GalaxyTimeMachine** [comment]
I went to take a screenshot, and after doing that, it forced the UI to start updating again?!

**Comment by GalaxyTimeMachine** [comment]
After changing the images again, it is back to not updating the UI. This screenshot was taken after generating from the 2 input images, yet the previous ones are still show.
![image](https://github.com/user-attachments/assets/340cb6af-824e-4478-a5cf-a65a26607a03)
The saved output was this...
![ComfyUI_00007_](https://github.com/user-attachments/assets/d4c45467-6d5b-4d29-b461-7f395d2a0138)

**Comment by diStyApps** [comment]
Cool images, i have tried the same, i don't have the same issue.
Can you upload a video of it.

**Comment by GalaxyTimeMachine** [comment]
> Cool images, i have tried the same, i don't have the same issue. Can you upload a video of it.

I can't seem to reproduce it again now. The version has upgraded to 0.4.1, so maybe something changed to fix it...?

**Comment by diStyApps** [comment]
I did a lot of changes not directly related to this flows, but all redux flows got updated.
