### ISSUE TITLE
[Bug]: All Interface BROKEN (only in Microsoft Edge)

### ISSUE THREAD

**Issue by ffdown** [diStyApps/ComfyUI-disty-Flow#26]
### Where is the issue?

- [ ] The issue is with the "Custom Node 'Flow'"
- [ ] The issue is with a specific flow. Please refer to [Flows repository](https://github.com/diStyApps/flows_lib) if the problem lies with a specific flow.
- [X] I’m not sure where the issue is

### Bug Description

update to 0.4.1 and all interface cleared
![image](https://github.com/user-attachments/assets/82280443-4514-45d4-83e7-776bb77aa2d0)

### Step-by-step instructions to reproduce the issue

this trouble in all workflow

### Expected Behavior

no bugs

### Current Behavior

not work

### Flow Version or Commit

0.4.1

### Media and Logs

```Shell
no
```

**Comment by diStyApps** [comment]
Try ctrl+F5, tell me if that worked?

**Comment by luxD3Br1** [comment]
Im using Opera /G Chrome, 

i updated the Node and saw that you have made the new flux dev fill inpainting worfklow available, nice but the same problem with this guy, when i click there's nothing in there.

I also wish you guys could get image to image(flux redux) based on prompts so  i can use them in start-end cogvideo

**Comment by ffdown** [comment]
> Try ctrl+F5, tell me if that worked?

so easy!!! Worked =))
