### ISSUE TITLE
[Feature Request]: Restore old mask and add batch

### ISSUE THREAD

**Issue by ffdown** [diStyApps/ComfyUI-disty-Flow#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Summary

1. Each time after generation, the mask is reset (flux detailer, flux inpaint) and you have to draw it again, in version 0.3.1. the mask did not disappear as 0.4.1, please return it.
2. I couldn’t find a way to generate several image options at once; only one image is drawn at a time.
3. automatic creation of masks based on Sam2.1 is definitely needed
4. Add the creation of a depth mask based on Lotus (by far the best depth analyzer) [https://github.com/kijai/ComfyUI-Lotus](url) there are also normal masks, although I still don’t understand how use them
5. Automatic generation of description based on QWEN https://github.com/IuvenisSapiens/ComfyUI_Qwen2-VL-Instruct previously used moondream and WD14, JoyTag, but compatibility problems very often arise with them.
6. And of course, changing the colors of the interface, because looking at purple on black is a pain!

### Description

6. blue, green, red, yellow, white

### Additional information

no

**Comment by diStyApps** [comment]
I see, can be annoying, it will be changed so the masks wont get cleared.
Also will be added a option live preview method or split view. (the old one)
In general will be added batching functionality.
Yes, i am planing to add functionality automatic creation of masks based on Sam2 and automatic descriptions
i will look into it https://github.com/kijai/ComfyUI-Lotus.

You can change themes or create your own right now.
![image_thems](https://github.com/user-attachments/assets/fb4cc423-698e-4b12-bd7e-e0411875359b)

Thank you for your suggestions.

**Comment by ffdown** [comment]
> Yes, i am planing to add functionality automatic creation of masks based on Sam2 and automatic descriptions
> i will look into it https://github.com/kijai/ComfyUI-Lotus.
One moment... ideal work only with model 1.5

> You can change themes or create your own right now.
If it hadn't been pointed out, I would never have seen it. Thank you

But what I'm looking forward to most in ComfyUI is when IC-LIght for FLUX starts working

**Comment by ffdown** [comment]
maybe Detail Daemon interested

**Comment by diStyApps** [comment]
The split screen is restored with previous functionality, you can access via the button "Switch View"
I will add IC-LIght for FLUX and check  Detail Daemon.
