### ISSUE TITLE
[Bug]: Flux dev fill inpainting stop comfy without error [CLOSED/UNRELATED WITH FLOW]

### ISSUE THREAD

**Issue by Hullabalo** [diStyApps/ComfyUI-disty-Flow#28]
### Where is the issue?

- [X] The issue is with the "Custom Node 'Flow'"
- [ ] The issue is with a specific flow. Please refer to [Flows repository](https://github.com/diStyApps/flows_lib) if the problem lies with a specific flow.
- [X] I’m not sure where the issue is

### Bug Description

First of all, thank you so much for your work! :)

I'm encountering an issue with the Flux Dev Fill Inpainting and Flux Dev Fill Detailed Inpainting workflows. Please note that I'm using the default workflow settings (no LoRa), right after launching Comfy, without loading any other workflows or intermediate models.

Thank you for your help!

### Step-by-step instructions to reproduce the issue

- Cold boot comfy
- go to 127.0.0.1/flow
- select the flow workflow (either Flux Dev Fill Inpainting or Flux Dev Fill Detailed Inpainting)
- loading an image (1024x1024)
-  selecting a small area to modify
- write a basic prompt ("man face")
- clicking on 'Generate' causes Comfy to stop working without showing any error in the console (as in screenshot). It seems to occur during the loading of CLIP.

### Expected Behavior

- normal model loading in memory

### Current Behavior

Comfy stop without errors

### Flow Version or Commit

0.4.1

### Media and Logs

```Shell
![Capture0312](https://github.com/user-attachments/assets/92af4ca3-9b56-4b83-89f9-619651d200f6)
```

### Additional Information

I tried loading T5xxl_fp8 instead of T5xxl_fp16, but without success.

Both RAM and VRAM remain available, so it seems the Flux model doesn’t have time to load before the crash. I don’t experience this issue with the equivalent workflow using GGUF (Q4_K_S). Usually I can do any non-Flow workflow without problems, including CogVideox etc.

My setup:

Stability Matrix (Comfy is up to date, and Flow freshly downloaded)
Windows 10
32GB RAM
RTX 3090

**Comment by Hullabalo** [comment]
OK, it seems that the classic workflows (which were still working yesterday with flux1-dev.safetensors) are now causing the same error as the one mentioned above, despite uninstalling disty-Flow. I must therefore assume that the reported error has nothing to do with ComfyUI-disty-Flow. Closed for now, I suppose.

**Comment by diStyApps** [comment]
Thank for reporting.
