### ISSUE TITLE
[Feature Request]: Add support for GGUF CLIPs (Clip L, T5XXL, etc)

### ISSUE THREAD

**Issue by LiteSoul** [diStyApps/ComfyUI-disty-Flow#29]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Summary

 Add support for GGUF CLIPs (Clip L, T5XXL, etc)

### Description

For those of us with limited VRAM, we use GGUF versions of Flux. Likewise we use GGUF versions of the CLIP files on regular ComfyUI, example:
t5-v1_1-xxl-encoder-Q5_K_M.gguf
clip_l-Q8_0.gguf

Please add support for this format, thanks.

**Comment by Hujikuio** [comment]
You can make / edit flows yourself so you're not just limited to the presets. I made one for myself however so [here you go.](https://github.com/diStyApps/ComfyUI-disty-Flow/discussions/36)

**Comment by diStyApps** [comment]
added
