### ISSUE TITLE
[Bug]: "Toggle" in Linker not assigning correct value

### ISSUE THREAD

**Issue by Hujikuio** [diStyApps/ComfyUI-disty-Flow#30]
### Where is the issue?

- [X] The issue is with the "Custom Node 'Flow'"
- [ ] The issue is with a specific flow. Please refer to [Flows repository](https://github.com/diStyApps/flows_lib) if the problem lies with a specific flow.
- [ ] I’m not sure where the issue is

### Bug Description

In the Linker, the default "true" seems to work fine, but I've tried "false", "False", and "0" and all 3 do not correctly set the default to off.

### Step-by-step instructions to reproduce the issue

This is for the Inpaint Crop and Stitch Node by lquesada, I have not tried any others yet. (https://github.com/lquesada/ComfyUI-Inpaint-CropAndStitch)

### Expected Behavior

Set to false

### Current Behavior

Set to true

### Flow Version or Commit

0.4.1 (Latest)

### Media and Logs

```Shell
N/A
```

### Additional Information

This node is absolutely amazing, and I've been waiting for something like this forever, thank you. I would like to see a Discussion tab opened up on this repo if possible to share flows, like the one I'm currently working on in this issue (It works fine, thankfully the toggle is non critical for most use cases). It's a auto inpaint with Grounding DINO and SAM + Crop and Stitch for lossless inpaints :)

Also a few tweaks to make the UI more usable on mobile would be awesome, but it already is infinitely more usable on mobile vs stock comfyui. You just have to zoom out a little bit but and deal with some workarounds. When I use my S Pen to select drop downs or text boxes, when I "un hover" the box after selecting it to go down to the keyboard pop up on my phone, it closes the keyboard because the box gets unselected, but I'm not sure if that's worth a bug report on its own, as I understand that mobile optimizations are probably not a priority right now.

**Comment by diStyApps** [comment]
Thank you very much. i will look into it.
I will open Discussion Tab You also can join discord: https://discord.gg/4w8yXGAq

The responsive layout and mobile optimizations are very high on my list and flow becoming more and more responsive. it is now usable on tablets and on mobile nice for basic generations but still no ideal, but is going there.
I want to use my S pan to draw on Flow, it will be very nice, already some people use flow for these uses and for my own uses, it is  kinda the reason i created flow, ComfyUI is amazing, but at real time production i found myself unproductive so it is very high priority.
Next updates will be focused on UI and canvas improvements.
These bug reports and suggestions helps me make Flow better so also some minor issues are worth to report.

**Comment by diStyApps** [comment]
Toggle is fixed, check it out.
