### ISSUE TITLE
[Feature Request]: Button that allows to switch to the Flow frontend from default ComfyUI frontend 

### ISSUE THREAD

**Issue by WanderFox** [diStyApps/ComfyUI-disty-Flow#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Summary

Hi! Could you add a simple button to the ComfyUI top panel that will switch the URL from Comfy's page to the Flow?

### Description

 I think some part of users use "App" feature in the browser that allows them to create Windows app from a web page. Also, there is a ComfyUI desktop app and LynxHub that allows you to work with ComfyUI not from a web browser but from an external app. Of course, I can open URL in a web browser but it will be really comfortable to switch between ComfyUI and Flow frontend with a single button click 
![image](https://github.com/user-attachments/assets/5112a492-7980-472c-af0d-c11f09babff0)

**Comment by LiJT** [comment]
Yeah! I hate manully typing /flow everytime i launch this awesome plugin

**Comment by diStyApps** [comment]
i will work on it.

**Comment by diStyApps** [comment]
Added 
![Screenshot 2024-12-15 at 11-20-30 Flow_05083_ - ComfyUI](https://github.com/user-attachments/assets/626f56eb-134b-48cf-9ba0-d8aa33bfc506)

**Comment by WanderFox** [comment]
Ty so much! This is really great news ^^
