### ISSUE TITLE
[Feature Request]: Extremely slow generation on 4090 due to lack of Flux quantization option for model loading, like comfyUI weight_dtype

### ISSUE THREAD

**Issue by LiJT** [diStyApps/ComfyUI-disty-Flow#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Summary

Hi, Thank you for your awesome plugin
I wish there is quantization option for Flux model, so user can toggle before each generation? Like this in ComfyUI
![PixPin_2024-12-09_13-36-44](https://github.com/user-attachments/assets/05ba8313-b286-4c17-8e8a-7687d2236d63)

### Description

![PixPin_2024-12-09_13-35-55](https://github.com/user-attachments/assets/c90e9a8b-913f-47d6-9f09-a858876da3cc)
So that the generation speed will be significantly faster? I just dont want to download a another specific fp8 model...

### Additional information

Thank you for your hard work!

**Comment by diStyApps** [comment]
Added to all the Redux Flows, later i will add to rest of them.

But for me is a lot faster in general with or without.
Tell me if that helped you.
![speed_flux png2](https://github.com/user-attachments/assets/a3f94e58-2fcd-4818-ac6f-c9d509e4a08c)

**Comment by LiJT** [comment]
> Added to all the Redux Flows, later i will add to rest of them.
> 
> But for me is a lot faster in general with or without. Tell me if that helped you. ![speed_flux png2](https://private-user-images.githubusercontent.com/3084832/393732184-a3f94e58-2fcd-4818-ac6f-c9d509e4a08c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3Mjc3NTYsIm5iZiI6MTczMzcyNzQ1NiwicGF0aCI6Ii8zMDg0ODMyLzM5MzczMjE4NC1hM2Y5NGU1OC0yZmNkLTQ4MTgtYWM2Zi1jOWQ1MDllNGEwOGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDlUMDY1NzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzM4NTVhMGU2OWY3NzhiOTM3NTZjM2JlNmJlN2JkOWEzZWZmYTQ1NzIxNGVkNmI4YTUwZmIzY2IwYmE2MWViZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.3fl7ctc50rWHtHJ7xCZ7UUCe-MDXXmJicFHywKJYCHs)

Thank you so much for your fast reply! yeat this is awesome!
