### ISSUE TITLE
[Bug]: Have to re-upload image to re-mask every time (Request? Bug?)

### ISSUE THREAD

**Issue by Hujikuio** [diStyApps/ComfyUI-disty-Flow#37]
### Where is the issue?

- [ ] The issue is with the "Custom Node 'Flow'"
- [ ] The issue is with a specific flow. Please refer to [Flows repository](https://github.com/diStyApps/flows_lib) if the problem lies with a specific flow.
- [ ] I’m not sure where the issue is

### Bug Description

If I regenerate an inpaint, either by pressing Generate or by trying to redraw the mask, it uses the old generation instead. Can there be a toggle to reuse the original image, or have the original image appear in the recents tab so you can drag it back to the canvas?

Additionally, these don't seem to be working right now, which is preferable, as I implemented blur and mask size in a workflow and would prefer to use that over the built in one (or it dynamically disables when it detects such behavior, and if that's the case, well done.). If they ARE working or will work in the future, could these be toggled off as well for custom workflow compatibility?
![image](https://github.com/user-attachments/assets/8285e895-6d3f-46e7-84f2-45054e9f4b7e)

***
Initial image:
![image](https://github.com/user-attachments/assets/eaf2770b-b301-4659-9923-eb70d7f5cfc9)
Mask 1:
![image](https://github.com/user-attachments/assets/4dbf0a11-64db-45bc-9923-dd964c72e873)
Finished Inpaint:
![image](https://github.com/user-attachments/assets/8af732ec-413d-47e2-a60b-75221185db55)
Denoise set to 0 (to see if it is using the original image still or the newly inpainted one)
![image](https://github.com/user-attachments/assets/5dc757cd-2b2f-4ef5-acc1-1020958e2a6e)
Not gonna upload the same image twice, but it is indeed using the new image instead of the original one, which I believe IS intended behavior. However the "Recents" tab does not have the original image, leading to having to re-upload the image 

### Step-by-step instructions to reproduce the issue

see above

### Expected Behavior

see above

### Current Behavior

see above

### Flow Version or Commit

0.4.5

### Media and Logs

```Shell
see above
```

### Additional Information

Thanks for this awesome extension :)

**Comment by Hujikuio** [comment]
I think I figured out the masking sticking? You must have the split panel view open before you generate, or else the above behavior occurs.

**Comment by diStyApps** [comment]
Yes, it is not really a bug, but not best functionality, i will sort it out soon.
The the image dropping from "recent" section depends on chrome built-in functionality, i will fix it to work on all browsers 
To the cropped image added a blur, you can remove the blur by setting it to 0, i can add a toggle , or maybe it just remember that last setting added.
Also a dynamic padding added to the image, i can expose them too for better custom workflow compatibility.
Mainly these are the issues i am working on, so you might see changes soon.

**Comment by Hujikuio** [comment]
Yup sounds good. I agree with wanting mask options to save state / have presets / have a toggle, but that would be more of a feature request. Closing.
