### ISSUE TITLE
[Bug]: Cannot properly generate video during "VideoCombine" phase in Hunyuan Text to Video workflow

### ISSUE THREAD

**Issue by LiJT** [diStyApps/ComfyUI-disty-Flow#38]
### Where is the issue?

- [X] The issue is with the "Custom Node 'Flow'"
- [X] The issue is with a specific flow. Please refer to [Flows repository](https://github.com/diStyApps/flows_lib) if the problem lies with a specific flow.
- [X] I’m not sure where the issue is

### Bug Description

![PixPin_2024-12-21_17-02-23](https://github.com/user-attachments/assets/aeb9ad24-c98f-43e9-ae4a-8393ff69b965)

### Step-by-step instructions to reproduce the issue

I cannot properly generate video during phase in Hunyuan Text to Video workflow. The error I have attached above. 

PS: I also managed to find the original wf inside "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-disty-Flow\web\flows\pla14-hunyuan-text-to-video\wf.json", and it runs flawlessly. So i guess it is the flow kernal problem, maybe the Web browser cannot replay the video?

### Expected Behavior

Play video after each successful generation

### Current Behavior

It hangs, and stop at "Video Combine" phase, the flow UI interface cannot watch the generated video

### Flow Version or Commit

Commit 501b04d

### Media and Logs

```Shell
!!! Exception during processing !!!
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 408, in combine_video
    video_format = apply_format_widgets(format_ext, kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 90, in apply_format_widgets
    assert(w[0][0] in kwargs)
           ^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by LiJT** [comment]
I asked ChatGPT, he said its Video Combine Node has some format_ext missing, like mp4 or other format is not defined?

**Comment by diStyApps** [comment]
There was an updated related to the formats, previous Hunyuan flow got replaced, update flow, and see if to issue is solved.

**Comment by LiJT** [comment]
> There was an updated related to the formats, previous Hunyuan flow got replaced, update flow, and see if to issue is solved.

Unfortunately no success man, I tired updated everything, VideoHelperSuite Node just wont allow to progress further, Still no video in browser and No video file in the output folder neither, only the very first frame saved in output folder

```
loaded completely 9.5367431640625e+25 470.1210079193115 True
!!! Exception during processing !!!
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 408, in combine_video
    video_format = apply_format_widgets(format_ext, kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 90, in apply_format_widgets
    assert(w[0][0] in kwargs)
           ^^^^^^^^^^^^^^^^^
AssertionError

Prompt executed in 52.73 seconds
```

**Comment by LiJT** [comment]
Just FYI i was using your Hunyuan - Text to Video flow all the time

Also I m wondering the Flux Guidance inside this WF, does it control the value of ModelSamplingSD3? if so maybe you can rename it haha. Otherwise what does it do since in original wf there is no Flux guidance to be seen...
![PixPin_2024-12-22_01-10-59](https://github.com/user-attachments/assets/3219b7ef-a17e-479a-97fa-4c997d98a3ce)

Thanks for your effort man

**Comment by diStyApps** [comment]
Added ModelSampling, But still it is not saving right?

**Comment by ai-anchorite** [comment]
Had same issue.  Worked yesterday and then fails today with the same AssertionError.  

Confirm works again as expected after the VideoHelperSuite update and updating to Flow 0.4.9

**Comment by LiJT** [comment]
> Had same issue. Worked yesterday and then fails today with the same AssertionError.
> 
> Confirm works again as expected after the VideoHelperSuite update and updating to Flow 0.4.9

confirmed working again after updating VideoHelperSuite ! thanks @diStyApps !
