### ISSUE TITLE
[Feature Request]: Folder/Directory Nesting

### ISSUE THREAD

**Issue by Hujikuio** [diStyApps/ComfyUI-disty-Flow#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Summary

For people with lots of Loras, Models, Controlnets, or anything really, having nesting support helps a lot with finding the item you want, especially if the user has already set up directories with lots of folders. Right now it's overwhelming for me to find the correct model I want when I have lots of them. Even just having the file at the end be in bold or something to differentiate would help a lot.

This behavior can be seen in rgthree's global settings and pyss' loader nodes as seen here:
![image](https://github.com/user-attachments/assets/bc26a032-70d3-40cd-9300-b3809cc6c132)
 
<img width="933" alt="image" src="https://github.com/user-attachments/assets/d447226a-55d2-4a63-86e9-d277dbcf76df" />

### Description

current behavior:
![image](https://github.com/user-attachments/assets/d43f547f-9dd4-400a-b502-559318da9337)

**Comment by diStyApps** [comment]
Added
