### ISSUE TITLE
[Bug]:  Invalid Prompt

### ISSUE THREAD

**Issue by Kallamamran** [diStyApps/ComfyUI-disty-Flow#4]
### Where is the issue?

- [X] The issue is with the "Custom Node 'Flow'"
- [X] The issue is with a specific flow. Please refer to [Flows repository](https://github.com/diStyApps/flows_lib) if the problem lies with a specific flow.
- [ ] I’m not sure where the issue is

### Bug Description

No image generated in i2i. Error in console instead

### Step-by-step instructions to reproduce the issue

Add image (tried many resolutions), add prompt, click generate

### Expected Behavior

Image generated

### Current Behavior

No image generated and the following error in console:

```
got prompt
invalid prompt: {'type': 'invalid_prompt', 'message': 'Cannot execute because a node is missing the class_type property.', 'details': "Node ID '#1'", 'extra_info': {}}
```

### Flow Version or Commit

0.1.1

### Media and Logs

```Shell
got prompt
invalid prompt: {'type': 'invalid_prompt', 'message': 'Cannot execute because a node is missing the class_type property.', 'details': "Node ID '#1'", 'extra_info': {}
```

**Comment by diStyApps** [comment]
Is it "Base - Stable Diffusion - Image to Image"?
I have updated the workflow for other reason, check if that fix that, and please add a full screenshot of the Flow ui with problematic workflow.

**Comment by ivanoff13** [comment]
![Снимок](https://github.com/user-attachments/assets/55b9182d-f8e7-4512-a622-8fd95068a952)
this scheme does not work for me

**Comment by diStyApps** [comment]
Sorry for late reply.  It seems there is a node conflict. The node "FloodGate" is not part of my workflow. Please navigate to:

custom_nodes\ComfyUI-disty-Flow\web\flows\afl_base-fluxdggufi2i, where you'll find wf.json. Drag this file into ComfyUI, and check if you're getting the same error. If so, please upload a screenshot.

Alternatively, you can try installing a fresh, updated version of ComfyUI and updated of  ComfyUI Manager.
