### ISSUE TITLE
[Feature Request]: ComfyUI Model Manager implementation

### ISSUE THREAD

**Issue by SomeNiceDude** [diStyApps/ComfyUI-disty-Flow#40]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Summary

Replacing the simple Dropdown Menu for Models with ComfyUI Model Manager.

### Description

Not sure if technically possible, but instead of just having a dropdown menu for Loras and Checkpoints, it would be great if you could have a menu with Lora Previews similar to https://github.com/hayden-fr/ComfyUI-Model-Manager

Kinda like this:
![image](https://github.com/user-attachments/assets/909b5e68-f27e-4117-993e-5de965ee3fda)

**Comment by diStyApps** [comment]
Added
Nice mock-up i liked it.
I will also add gallery/tiled layout, also maybe it will be on separated tab.
