### ISSUE TITLE
[Bug]: Casic AnimateDiff workflow - missing custom node ComfyUI Impact Pack

### ISSUE THREAD

**Issue by ceramicv** [diStyApps/ComfyUI-disty-Flow#6]
### Where is the issue?

- [ ] The issue is with the "Custom Node 'Flow'"
- [ ] The issue is with a specific flow. Please refer to [Flows repository](https://github.com/diStyApps/flows_lib) if the problem lies with a specific flow.
- [X] I’m not sure where the issue is

### Bug Description

When loading this flow I get a box that says "Nodes Unavailable" and it refers to the ComfyUI Impact Pack which i do have installed but I tried installing again using the button in that box, restarted and got the same message, so i uninstalled and went directly to the URL offered : https://github.com/ltdrdata/ComfyUI-Impact-Pack  and installed from there, restarted - same error

### Step-by-step instructions to reproduce the issue

![image](https://github.com/user-attachments/assets/01fe2244-81b8-4128-9326-09a0d2e83ca7)

### Expected Behavior

N/A

### Current Behavior

N/A

### Flow Version or Commit

Not sure how to tell, downloaded today

### Media and Logs

```Shell
N/A
```

**Comment by diStyApps** [comment]
Please update ComfyUI and ComfyUI Manager, and try install ComfyUI Impact Pack again.
If that didn't work try to install ComfyUI Impact Pack via the ComfyUI Manager
Also please add screen shot of of the loaded custom nodes on ComfyUI when starting.

**Comment by jandolina** [comment]
I am seeing this too with 0.1.2 and 0.1.3.
![Screenshot 2024-10-25 at 12 11 39 PM](https://github.com/user-attachments/assets/2a629b41-936e-4f77-a29a-5d208ec1ebc7)
![Screenshot 2024-10-25 at 12 11 07 PM](https://github.com/user-attachments/assets/f8b82633-505d-4ff7-9b5e-5fa51a0acb93)

**Comment by diStyApps** [comment]
I fixed check it, see if it solved for you.
