### ISSUE TITLE
[Bug]: Model Locations and Missing Models

### ISSUE THREAD

**Issue by jandolina** [diStyApps/ComfyUI-disty-Flow#7]
### Where is the issue?

- [ ] The issue is with the "Custom Node 'Flow'"
- [ ] The issue is with a specific flow. Please refer to [Flows repository](https://github.com/diStyApps/flows_lib) if the problem lies with a specific flow.
- [ ] I’m not sure where the issue is

### Bug Description

I am not seeing my models in the Flow UI. My model is a symbolic link from /home/ComfyUI/models to /home/models. It is finding my vae models but not my checkpoints and the t5xxl... models

### Step-by-step instructions to reproduce the issue

Are there any settings?

### Expected Behavior

I would see my models populate the pulldowns

### Current Behavior

For simple Flux Dev, the top two pulldowns are empty

### Flow Version or Commit

current

### Media and Logs

```Shell
No more...
```

**Comment by diStyApps** [comment]
Should have not have problems with symbolic link, i also use it.
In what workflow it happening?
In ComfyUI its working properly?

**Comment by jandolina** [comment]
It seems it has to do with the Flux workflows. The Basic SDXL workflows show all my models and are working fine. The pulldowns for model and ClipLoader 1 on the Flux workflows seem to be filtering the results.

**Comment by jandolina** [comment]
You can see below that the models are in the right place and showing up for the SDXL workflows. 
![Screenshot 2024-10-23 at 9 56 54 PM](https://github.com/user-attachments/assets/7962951b-275c-4ec1-b827-ef3ca01ebf73)

**Comment by diStyApps** [comment]
For flux models should be in the folder "unet" and the clip models in "clip" folder inside the models folder in ComfyUI.

**Comment by jandolina** [comment]
That was it, thank you!
