### ISSUE TITLE
[Feature Request]: Is it possible to view steps / diffusion during generation?

### ISSUE THREAD

**Issue by spiritform** [diStyApps/ComfyUI-disty-Flow#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Summary

I'm just curious if it's possible to show the diffusion steps during image generation from the ksampler, instead of just showing the preview / saved image.

### Description

Right now it shows the image when the progress bar reaches the end and I was curious if you can show the image being diffused like you can in comfy ui ksampler (advanced)

**Comment by diStyApps** [comment]
added
